name: Deploy to Coolify

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.REGISTRY_URL }}/vergabedokument-generator:latest
          ${{ secrets.REGISTRY_URL }}/vergabedokument-generator:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Coolify
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.COOLIFY_WEBHOOK_URL }}
        method: 'POST'
        customHeaders: '{"Authorization": "Bearer ${{ secrets.COOLIFY_TOKEN }}"}'
        data: '{"force": true}'

    - name: Health Check
      run: |
        echo "Waiting for deployment to be ready..."
        sleep 30
        curl -f ${{ secrets.APP_URL }}/api/health || exit 1
        echo "✅ Deployment successful!"